name: mutation test

on:
  pull_request:
  push:
    branches: ['master']

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mutation:
    name: PHP ${{ matrix.php }}-${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
        php:
          - "8.5"
    
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        env:
          update: true
        with:
          php-version: ${{ matrix.php }}
          ini-values: memory_limit=-1
          coverage: xdebug

      - name: Install Composer dependencies
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0

      - name: Run infection
        run: vendor/bin/infection --threads=max --ignore-msi-with-no-mutations
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
