name: tests

on:
  pull_request:
  push:
    branches: ['master']

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  phpunit:
    name: PHP ${{ matrix.php }}-${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        php:
          - "8.2"
          - "8.3"
          - "8.4"
          - "8.5"

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        env:
          update: true
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          extensions: openssl, sodium

      - name: Install Composer dependencies
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0

      - name: Run tests with PHPUnit
        run: vendor/bin/phpunit --colors=always --coverage-clover=coverage.xml

      - name: Upload coverage to Coveralls
        if: matrix.os == 'ubuntu-latest'
        uses: coverallsapp/github-action@v2
        with:
          file: ./coverage.xml

  phpunit-without-openssl-sodium:
    name: PHP 8.2 without openssl and sodium

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      - name: Install Composer dependencies
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0

      - name: Prepare PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: :openssl, :sodium

      - name: Run tests with PHPUnit
        run: vendor/bin/phpunit --colors=always
